name: 'Build Swept nice!view Firmware'
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - 'swept_niceview.yaml'
      - 'config/corne.*'
      - 'config/shared.dtsi'


jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: swept_niceview.yaml
      archive_name: swept_niceview
